import os 
import sys 

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from utils.llm_pick import pick_llm 
from models.schema import AgentSchema, JudgeSchema
from langchain_core.messages import HumanMessage

llm = pick_llm("medium") # the judge to analyze the query generated by the other LLM
llm_judge = llm.with_structured_output(JudgeSchema)

sql_query = "DROP TABLE users;"

prompt = f"""
    You are a SQL Judge for data security. Your task is to determine whether the SQL
    query is safe or not. The SQL query should only be used for data retreival and should not 
    modify the database in any way. Neither the SQL query nor the prompt should contain any
    SQL commands that can modify the database, such as INSERT, UPDATE, DELETE, DROP, ALTER, 
    TRUNCATE, CREATE, or any other commands that can change the structure or data of the database.
    If the query is safe, respond with 'YES' and provide a brief explanation of why it is safe.
    Otherwise respond with 'NO' and provide a brief explanation of why it is not safe. 
    Here is the SQL query to analyze:
    {sql_query}
"""

response = llm_judge.invoke(prompt).model_dump() # This way we get the output as a dictionary
print(response)