from pydantic import BaseModel, Field
from typing import Annotated, Literal
from operator import add 


class AgentSchema(BaseModel):
    messages : Annotated[list, add] = Field(..., description="List of messages to be processed by the agent")
    user_question : str = Field(..., description="The original question asked by the user")
    curated_ques : str = Field(..., description="Curated question to be answered by the agent")
    prompt_query : str = Field(..., description="A detailed prompt with SQL DB context")
    is_safe : Literal["YES", "NO"] = Field(..., description="Indicates whether the generated SQL query is safe or not")
    generated_sql_query : str = Field(..., description="The SQL query generated by the agent based on the curated question and context")
    comments : str = Field(..., description="Additional comments or feedback regarding safety ofthe generated SQL query")
    sql_query_execution_result : str = Field(..., description="The result of executing the generated SQL query on the database")
    final_answer : str = Field(..., description="The final answer provided by the agent after processing the messages and executing the SQL query")


class JudgeSchema(BaseModel): 
    answer : Literal["YES", "NO"] = Field(..., description="Indicates whether the final answer provided by the agent is correct or not")
    comments : str = Field(..., description="Additional comments or feedback regarding the final answer provided by the agent")

class ETLAgentSchema(BaseModel): 
    messages: Annotated[list, add] = Field(..., description="List of messages to be procesed by the ETL agent")


class RouterSchema(BaseModel): 
    answer: Literal["sql", "etl"] = Field(..., description="Indicated whether the user's question is related to the sql_analyst agent or etl_analyst agent")
    comments: str = Field(..., description="Additional comments or feedback regarding the classification of the user's question")

class DataEngineerSchema(BaseModel): 
    messages: Annotated[list, add] = Field(..., description="List of messages to be processed by the data engineer agent")
    route_response: str = Field(..., description="The response from the router indicating whether the user's question needs the etl_analyst or sql_analyst agent")
    